const MONGODB_URL = ''

const GOOGLE_PLACES_API_KEY = ''
const GOOGLE_DIRECTIONS_API_KEY = ''
const GOOGLE_SHEETS_API_KEY = ''
const GOOGLE_WEB_AUTH_CLIENT_ID = ''
const GOOGLE_IOS_AUTH_CLIENT_ID = ''

module.exports = {
    MONGODB_URL,
    GOOGLE_PLACES_API_KEY,
    GOOGLE_DIRECTIONS_API_KEY,
    GOOGLE_SHEETS_API_KEY,
    GOOGLE_WEB_AUTH_CLIENT_ID,
    GOOGLE_IOS_AUTH_CLIENT_ID
}